In [1]:
##IWF Daten 2

In [2]:
import pandas as pd

In [3]:
df3 = pd.read_csv('IWF_bereinigt.csv')

In [4]:
df3

,country,Indicator,PRIMARY_DOMESTIC_CURRENCY,2001,2002,2003,2004,2005,2006,2007,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Slovak Republic,"Gross domestic product (GDP), Constant prices,...",Euro,48.538,50.682,53.144,56.008,59.640,64.964,71.992,...,88.432,90.974,94.669,96.824,94.321,99.655,100.198,102.315,104.298,105.141
1,"Estonia, Republic of","Gross debt, General government, Percent of GDP",Euro,4.933,5.660,5.599,5.159,4.733,4.717,3.908,...,10.239,9.434,8.507,9.047,19.098,18.425,19.112,20.274,23.451,23.965
2,Czech Republic,"Gross debt, General government, Percent of GDP",Czech koruna,22.597,25.703,28.062,28.289,27.678,27.565,27.346,...,36.232,33.782,31.678,29.552,36.883,40.692,42.520,42.223,43.232,44.166
3,Czech Republic,"Gross domestic product (GDP), Constant prices,...",Czech koruna,3750.216,3806.974,3932.636,4118.899,4381.480,4671.673,4928.093,...,5495.050,5779.340,5942.913,6154.824,5828.318,6063.142,6235.770,6238.737,6320.676,6486.784
4,"Latvia, Republic of","Gross domestic product (GDP), Constant prices,...",Euro,16.482,17.745,19.241,20.920,23.350,26.345,29.088,...,27.881,28.829,30.072,30.275,29.224,31.253,31.850,31.550,31.538,32.212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,Israel,"Gross debt, General government, Percent of GDP",Israeli new shekel,81.416,87.642,90.048,88.734,85.669,78.047,71.201,...,62.040,60.125,60.340,59.543,71.376,68.193,60.884,61.920,67.677,67.869
110,Israel,"Gross domestic product (GDP), Constant prices,...",Israeli new shekel,0.318,-0.250,1.563,4.567,4.300,5.598,6.263,...,4.544,4.339,4.108,3.645,-1.884,8.956,6.147,2.049,1.711,3.486
111,"Korea, Republic of","Gross debt, General government, Percent of GDP",South Korean won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39.144,38.011,37.854,39.730,45.915,47.949,49.704,50.562,49.558,52.417
112,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,1045467.700,1126428.700,1161063.300,1221248.600,1274473.400,1341319.600,1419679.000,...,1898551.100,1963732.000,2026102.400,2072982.300,2058466.400,2155142.800,2217828.200,2250707.400,2300068.700,2326267.400
113,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,4.726,7.744,3.075,5.184,4.358,5.245,5.842,...,3.172,3.433,3.176,2.314,-0.700,4.697,2.909,1.482,2.193,1.139

In [5]:
df3.dtypes

country                       object
Indicator                     object
PRIMARY_DOMESTIC_CURRENCY     object
2001                         float64
2002                         float64
2003                         float64
2004                         float64
2005                         float64
2006                         float64
2007                         float64
2008                         float64
2009                         float64
2010                         float64
2011                         float64
2012                         float64
2013                         float64
2014                         float64
2015                         float64
2016                         float64
2017                         float64
2018                         float64
2019                         float64
2020                         float64
2021                         float64
2022                         float64
2023                         float64
2024                         float64
2025                         float64
dtype: object

In [6]:
##auf Duplikate überprüfen

df3.duplicated().sum()

0

In [7]:
df3.duplicated(subset=['country', 'Indicator']).sum()

0

In [8]:
df3

,country,Indicator,PRIMARY_DOMESTIC_CURRENCY,2001,2002,2003,2004,2005,2006,2007,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Slovak Republic,"Gross domestic product (GDP), Constant prices,...",Euro,48.538,50.682,53.144,56.008,59.640,64.964,71.992,...,88.432,90.974,94.669,96.824,94.321,99.655,100.198,102.315,104.298,105.141
1,"Estonia, Republic of","Gross debt, General government, Percent of GDP",Euro,4.933,5.660,5.599,5.159,4.733,4.717,3.908,...,10.239,9.434,8.507,9.047,19.098,18.425,19.112,20.274,23.451,23.965
2,Czech Republic,"Gross debt, General government, Percent of GDP",Czech koruna,22.597,25.703,28.062,28.289,27.678,27.565,27.346,...,36.232,33.782,31.678,29.552,36.883,40.692,42.520,42.223,43.232,44.166
3,Czech Republic,"Gross domestic product (GDP), Constant prices,...",Czech koruna,3750.216,3806.974,3932.636,4118.899,4381.480,4671.673,4928.093,...,5495.050,5779.340,5942.913,6154.824,5828.318,6063.142,6235.770,6238.737,6320.676,6486.784
4,"Latvia, Republic of","Gross domestic product (GDP), Constant prices,...",Euro,16.482,17.745,19.241,20.920,23.350,26.345,29.088,...,27.881,28.829,30.072,30.275,29.224,31.253,31.850,31.550,31.538,32.212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,Israel,"Gross debt, General government, Percent of GDP",Israeli new shekel,81.416,87.642,90.048,88.734,85.669,78.047,71.201,...,62.040,60.125,60.340,59.543,71.376,68.193,60.884,61.920,67.677,67.869
110,Israel,"Gross domestic product (GDP), Constant prices,...",Israeli new shekel,0.318,-0.250,1.563,4.567,4.300,5.598,6.263,...,4.544,4.339,4.108,3.645,-1.884,8.956,6.147,2.049,1.711,3.486
111,"Korea, Republic of","Gross debt, General government, Percent of GDP",South Korean won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39.144,38.011,37.854,39.730,45.915,47.949,49.704,50.562,49.558,52.417
112,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,1045467.700,1126428.700,1161063.300,1221248.600,1274473.400,1341319.600,1419679.000,...,1898551.100,1963732.000,2026102.400,2072982.300,2058466.400,2155142.800,2217828.200,2250707.400,2300068.700,2326267.400
113,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,4.726,7.744,3.075,5.184,4.358,5.245,5.842,...,3.172,3.433,3.176,2.314,-0.700,4.697,2.909,1.482,2.193,1.139

In [9]:
##keine Duplikate, bereit für melt (Umtausch von Zeilen und Spalten)

jahre = [str(i) for i in range(2001, 2026)]

df_sql = df3.melt(
    id_vars=['country', 'Indicator', 'PRIMARY_DOMESTIC_CURRENCY'],
    value_vars=jahre,
    var_name='year',
    value_name='value'
)

In [10]:
df_sql

,country,Indicator,PRIMARY_DOMESTIC_CURRENCY,year,value
0,Slovak Republic,"Gross domestic product (GDP), Constant prices,...",Euro,2001,48.538
1,"Estonia, Republic of","Gross debt, General government, Percent of GDP",Euro,2001,4.933
2,Czech Republic,"Gross debt, General government, Percent of GDP",Czech koruna,2001,22.597
3,Czech Republic,"Gross domestic product (GDP), Constant prices,...",Czech koruna,2001,3750.216
4,"Latvia, Republic of","Gross domestic product (GDP), Constant prices,...",Euro,2001,16.482
...,...,...,...,...,...
2845,Israel,"Gross debt, General government, Percent of GDP",Israeli new shekel,2025,67.869
2846,Israel,"Gross domestic product (GDP), Constant prices,...",Israeli new shekel,2025,3.486
2847,"Korea, Republic of","Gross debt, General government, Percent of GDP",South Korean won,2025,52.417
2848,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,2025,2326267.400
2849,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,2025,1.139

In [11]:
df_sql.dtypes

country                       object
Indicator                     object
PRIMARY_DOMESTIC_CURRENCY     object
year                          object
value                        float64
dtype: object

In [12]:
##nochmal die Types checken
##year als INT speichern

df_sql['year'] = df_sql['year'].astype(int)

In [13]:
import os
print(os.getcwd())

C:\Users\phili\Final Project

In [14]:
df_sql.to_csv(
    'IWF_MySQL.csv',
    index=False,
    encoding='utf-8',
    na_rep=''
)

In [15]:
##'SQL Datei ist als csv gespeichert - Datenbereinigung abgeschlossen

In [16]:
##Liste der Länder im IWF Datensatz

df_sql['country'].unique()

array(['Slovak Republic', 'Estonia, Republic of', 'Czech Republic',
       'Latvia, Republic of', 'Hungary', 'Lithuania, Republic of',
       'Slovenia, Republic of', 'Poland, Republic of', 'United Kingdom',
       'United States', 'Belgium', 'Austria', 'Germany', 'Denmark',
       'France', 'Luxembourg', 'Italy', 'Sweden', 'Norway',
       'Netherlands, The', 'Switzerland', 'Canada', 'Japan', 'Finland',
       'Iceland', 'Greece', 'Ireland', 'Spain', 'Portugal', 'New Zealand',
       'Australia', 'Türkiye, Republic of', 'Colombia', 'Chile',
       'Costa Rica', 'Mexico', 'Israel', 'Korea, Republic of'],
      dtype=object)

In [17]:
liste = list(df_sql['country'].unique())

In [18]:
liste

['Slovak Republic',
 'Estonia, Republic of',
 'Czech Republic',
 'Latvia, Republic of',
 'Hungary',
 'Lithuania, Republic of',
 'Slovenia, Republic of',
 'Poland, Republic of',
 'United Kingdom',
 'United States',
 'Belgium',
 'Austria',
 'Germany',
 'Denmark',
 'France',
 'Luxembourg',
 'Italy',
 'Sweden',
 'Norway',
 'Netherlands, The',
 'Switzerland',
 'Canada',
 'Japan',
 'Finland',
 'Iceland',
 'Greece',
 'Ireland',
 'Spain',
 'Portugal',
 'New Zealand',
 'Australia',
 'Türkiye, Republic of',
 'Colombia',
 'Chile',
 'Costa Rica',
 'Mexico',
 'Israel',
 'Korea, Republic of']