In [55]:
###Data Cleaning Daten IWF

In [56]:
import pandas as pd
import numpy as np

In [57]:
df = pd.read_csv(r'C:\Users\phili\OneDrive\Desktop\Abschlussarbeit Weiterbildung\datasets\IWF - World Economic Outlook.csv', 
                low_memory = False)

In [58]:
df.columns

Index(['DATASET', 'SERIES_CODE', 'OBS_MEASURE', 'COUNTRY', 'INDICATOR',
       'FREQUENCY', 'SCALE', 'UNIT', 'COUNTRY_UPDATE_DATE', 'PUBLICATION_DATE',
       'UPDATE_DATE', 'METHODOLOGY', 'METHODOLOGY_NOTES',
       'LATEST_ACTUAL_ANNUAL_DATA', 'HISTORICAL_DATA_SOURCE', 'BASE_YEAR',
       'START_END_MONTHS_OF_REPORTING_YEAR', 'CHAIN_WEIGHTED',
       'BASIS_OF_PROJECTIONS', 'VALUATION', 'PRICES_SECTOR_HARMONIZED_PRICES',
       'LABOR_SECTOR_EMPLOYMENT_TYPE',
       'FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION',
       'FISCAL_SECTOR_VALUATION_OF_DEBT',
       'FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT',
       'TRADE_SECTOR_OIL_COVERAGE', 'PRIMARY_DOMESTIC_CURRENCY', '1980',
       '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989',
       '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998',
       '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007',
       '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016',
       '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024', '2025',
       '2026', '2027', '2028', '2029', '2030', '2031'],
      dtype='object')

In [59]:
##mehrere Dateien auswählen

In [60]:
df.iloc[:, 0]

0       IMF.RES:WEO(9.0.0)
1       IMF.RES:WEO(9.0.0)
2       IMF.RES:WEO(9.0.0)
3       IMF.RES:WEO(9.0.0)
4       IMF.RES:WEO(9.0.0)
               ...
8197    IMF.RES:WEO(9.0.0)
8198    IMF.RES:WEO(9.0.0)
8199    IMF.RES:WEO(9.0.0)
8200    IMF.RES:WEO(9.0.0)
8201    IMF.RES:WEO(9.0.0)
Name: DATASET, Length: 8202, dtype: object

In [61]:
liste = [i for i in range(0, 30)]
liste

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [62]:
df.iloc[:, liste]

##nur 'country' ist wert berücksichtigt zu werden
##range(10,25) ist nutzlos
##Jahreszahl beginnt ab 27 und geht bis 79 -> Jahr 2031
##primary domestic currency

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,UNIT,COUNTRY_UPDATE_DATE,PUBLICATION_DATE,...,PRICES_SECTOR_HARMONIZED_PRICES,LABOR_SECTOR_EMPLOYMENT_TYPE,FISCAL_SECTOR_GENERAL_GOVERNMENT_COMPOSITION,FISCAL_SECTOR_VALUATION_OF_DEBT,FISCAL_SECTOR_INSTRUMENTS_INCLUDED_IN_GROSS_AND_NET_DEBT,TRADE_SECTOR_OIL_COVERAGE,PRIMARY_DOMESTIC_CURRENCY,1980,1981,1982
0,IMF.RES:WEO(9.0.0),SYR.GGX_NGDP.A,OBS_VALUE,Syrian Arab Republic,"Expenditure, General government, Percent of GDP",Annual,Units,Percent,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,Central Government,Face value,NaN,NaN,Syrian pound,NaN,NaN,NaN
1,IMF.RES:WEO(9.0.0),SYR.PPPPC.A,OBS_VALUE,Syrian Arab Republic,"Gross domestic product (GDP), Per capita, purc...",Annual,Units,NaN,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2072.834,2378.938,2507.588
2,IMF.RES:WEO(9.0.0),SYR.GGR_NGDP.A,OBS_VALUE,Syrian Arab Republic,"Revenue, General government, Percent of GDP",Annual,Units,Percent,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,Central Government,Face value,NaN,NaN,Syrian pound,NaN,NaN,NaN
3,IMF.RES:WEO(9.0.0),SYR.PCPIE.A,OBS_VALUE,Syrian Arab Republic,"All Items, Consumer price index (CPI), End-of-...",Annual,Units,Index,NaN,2026-10-13T02:00:00Z,...,No,NaN,NaN,NaN,NaN,NaN,Syrian pound,NaN,NaN,NaN
4,IMF.RES:WEO(9.0.0),SYR.PPPGDP.A,OBS_VALUE,Syrian Arab Republic,"Gross domestic product (GDP), Current prices, ...",Annual,Billions,NaN,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.923,22.466,24.470
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8197,IMF.RES:WEO(9.0.0),SYC.TX_RPCH.A,OBS_VALUE,Seychelles,"Exports of goods and services, Volume, Free on...",Annual,Units,Percent,9/25/2026,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,Secondary or refined products,Seychelles rupee,-1.387,-24.885,-12.680
8198,IMF.RES:WEO(9.0.0),SYC.NGDP_FY.A,OBS_VALUE,Seychelles,"Gross domestic product (GDP), Current prices, ...",Annual,Billions,Domestic currency,9/25/2026,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,Seychelles rupee,0.942,0.972,0.968
8199,IMF.RES:WEO(9.0.0),SLE.PCPIPCH.A,OBS_VALUE,Sierra Leone,"All Items, Consumer price index (CPI), Period ...",Annual,Units,Percent,9/25/2026,2026-10-13T02:00:00Z,...,No,NaN,NaN,NaN,NaN,NaN,Sierra Leonean leone,12.867,23.369,26.890
8200,IMF.RES:WEO(9.0.0),SEN.GGXCNL_NGDP.A,OBS_VALUE,Senegal,"Net lending (+) / net borrowing (-), General g...",Annual,Units,Percent,9/29/2026,2026-10-13T02:00:00Z,...,NaN,NaN,Central Government,Nominal value,NaN,NaN,CFA franc,NaN,NaN,NaN
8201,IMF.RES:WEO(9.0.0),SEN.PPPEX.A,OBS_VALUE,Senegal,"Rate, Domestic currency per international doll...",Annual,Units,NaN,9/29/2026,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.583,160.810,166.244

In [63]:
df.iloc[:, -1]

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
         ...
8197     3.478
8198    46.433
8199     9.000
8200       NaN
8201       NaN
Name: 2031, Length: 8202, dtype: float64

In [64]:
df.shape

(8202, 79)

In [65]:
##Spalten , die ausgewähölt werden sollen -> country, primary domestic currency, allg. Spalten von 3,4  24,25 bis 79

In [66]:
df

,DATASET,SERIES_CODE,OBS_MEASURE,COUNTRY,INDICATOR,FREQUENCY,SCALE,UNIT,COUNTRY_UPDATE_DATE,PUBLICATION_DATE,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,IMF.RES:WEO(9.0.0),SYR.GGX_NGDP.A,OBS_VALUE,Syrian Arab Republic,"Expenditure, General government, Percent of GDP",Annual,Units,Percent,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,IMF.RES:WEO(9.0.0),SYR.PPPPC.A,OBS_VALUE,Syrian Arab Republic,"Gross domestic product (GDP), Per capita, purc...",Annual,Units,NaN,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,IMF.RES:WEO(9.0.0),SYR.GGR_NGDP.A,OBS_VALUE,Syrian Arab Republic,"Revenue, General government, Percent of GDP",Annual,Units,Percent,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,IMF.RES:WEO(9.0.0),SYR.PCPIE.A,OBS_VALUE,Syrian Arab Republic,"All Items, Consumer price index (CPI), End-of-...",Annual,Units,Index,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,IMF.RES:WEO(9.0.0),SYR.PPPGDP.A,OBS_VALUE,Syrian Arab Republic,"Gross domestic product (GDP), Current prices, ...",Annual,Billions,NaN,NaN,2026-10-13T02:00:00Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8197,IMF.RES:WEO(9.0.0),SYC.TX_RPCH.A,OBS_VALUE,Seychelles,"Exports of goods and services, Volume, Free on...",Annual,Units,Percent,9/25/2026,2026-10-13T02:00:00Z,...,2.667,9.285,-2.678,17.936,-5.886,5.544,2.923,2.764,2.486,3.478
8198,IMF.RES:WEO(9.0.0),SYC.NGDP_FY.A,OBS_VALUE,Seychelles,"Gross domestic product (GDP), Current prices, ...",Annual,Billions,Domestic currency,9/25/2026,2026-10-13T02:00:00Z,...,28.544,30.441,32.381,34.341,34.901,37.228,39.371,41.631,44.021,46.433
8199,IMF.RES:WEO(9.0.0),SLE.PCPIPCH.A,OBS_VALUE,Sierra Leone,"All Items, Consumer price index (CPI), Period ...",Annual,Units,Percent,9/25/2026,2026-10-13T02:00:00Z,...,27.208,47.716,28.428,7.606,13.808,13.015,9.278,9.000,9.000,9.000
8200,IMF.RES:WEO(9.0.0),SEN.GGXCNL_NGDP.A,OBS_VALUE,Senegal,"Net lending (+) / net borrowing (-), General g...",Annual,Units,Percent,9/29/2026,2026-10-13T02:00:00Z,...,-16.076,-14.766,-13.682,-6.441,NaN,NaN,NaN,NaN,NaN,NaN
8201,IMF.RES:WEO(9.0.0),SEN.PPPEX.A,OBS_VALUE,Senegal,"Rate, Domestic currency per international doll...",Annual,Units,NaN,9/29/2026,2026-10-13T02:00:00Z,...,216.702,215.247,206.519,208.238,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
liste = [i for i in range(27,79)]
liste

[27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78]

In [68]:
df1 = df.iloc[:, [3,4, 26]]
df2 = df.iloc[:, liste]
df3 = pd.concat([df1, df2], axis = 1)

In [69]:
df3.iloc[1].unique()

array(['Syrian Arab Republic',
       'Gross domestic product (GDP), Per capita, purchasing power parity (PPP) international dollar, ICP benchmarks 2017-2021',
       nan, 2072.834, 2378.938, 2507.588, 2562.195, 2402.177, 2570.925,
       2417.881, 2426.469, 2739.199, 2587.213, 2863.504, 3182.508,
       3581.75, 3830.209, 4019.565, 4216.895, 4314.283, 4238.804,
       4418.468, 4236.195, 4318.787, 4457.101, 4662.01, 4523.967,
       4816.097, 5107.609, 5396.814, 5715.679, 5939.128, 6175.748,
       6374.969, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan], dtype=object)

In [70]:
df3 = df3.loc[(df3['INDICATOR'].str.contains('GDP') == True) | (df3['INDICATOR'].str.contains('PPP') == True), :].copy()

In [71]:
indikatoren = [
    'Gross domestic product (GDP), Constant prices, Domestic currency',
    'Gross domestic product (GDP), Constant prices, Percent change',
    'Gross debt, General government, Percent of GDP'
]


df3 = df3.loc[(df3['INDICATOR'].isin(indikatoren)), :].copy()

In [72]:
df3

,COUNTRY,INDICATOR,PRIMARY_DOMESTIC_CURRENCY,1980,1981,1982,1983,1984,1985,1986,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
14,Syrian Arab Republic,"Gross debt, General government, Percent of GDP",Syrian pound,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Syrian Arab Republic,"Gross domestic product (GDP), Constant prices,...",Syrian pound,464.241,503.530,516.534,524.824,490.720,526.524,501.478,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Syrian Arab Republic,"Gross domestic product (GDP), Constant prices,...",Syrian pound,10.493,8.463,2.583,1.605,-6.498,7.296,-4.757,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,"Eritrea, The State of","Gross domestic product (GDP), Constant prices,...",Eritrean nakfa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,"Eritrea, The State of","Gross domestic product (GDP), Constant prices,...",Eritrean nakfa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8173,"Mozambique, Republic of","Gross debt, General government, Percent of GDP",Mozambican metical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97.307,90.828,91.192,90.294,91.024,98.641,104.820,109.837,108.826,98.717
8180,Senegal,"Gross domestic product (GDP), Constant prices,...",CFA franc,3483.268,3659.852,3946.897,3736.670,3876.637,4003.925,4128.581,...,14797.900,15427.910,16424.893,17522.450,NaN,NaN,NaN,NaN,NaN,NaN
8186,Seychelles,"Gross domestic product (GDP), Constant prices,...",Seychelles rupee,5.342,5.135,5.029,4.998,5.213,5.750,5.793,...,24.942,26.233,27.112,28.678,28.971,30.137,31.084,32.048,33.062,34.119
8187,Seychelles,"Gross domestic product (GDP), Constant prices,...",Seychelles rupee,-2.253,-3.877,-2.071,-0.616,4.306,10.294,0.762,...,9.877,5.176,3.351,5.776,1.020,4.027,3.141,3.101,3.164,3.197
8191,Seychelles,"Gross debt, General government, Percent of GDP",Seychelles rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,60.563,55.106,56.252,51.205,52.747,51.980,51.043,49.965,48.810,47.705

In [73]:
##Merksätze zu den Indikatoren

df3 = df3.rename(columns = {'INDICATOR' : 'Indicator'})

In [74]:
df3 = df3.reset_index().copy()

In [75]:
df3

,index,COUNTRY,Indicator,PRIMARY_DOMESTIC_CURRENCY,1980,1981,1982,1983,1984,1985,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,14,Syrian Arab Republic,"Gross debt, General government, Percent of GDP",Syrian pound,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,18,Syrian Arab Republic,"Gross domestic product (GDP), Constant prices,...",Syrian pound,464.241,503.530,516.534,524.824,490.720,526.524,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,33,Syrian Arab Republic,"Gross domestic product (GDP), Constant prices,...",Syrian pound,10.493,8.463,2.583,1.605,-6.498,7.296,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,47,"Eritrea, The State of","Gross domestic product (GDP), Constant prices,...",Eritrean nakfa,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,59,"Eritrea, The State of","Gross domestic product (GDP), Constant prices,...",Eritrean nakfa,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,8173,"Mozambique, Republic of","Gross debt, General government, Percent of GDP",Mozambican metical,NaN,NaN,NaN,NaN,NaN,NaN,...,97.307,90.828,91.192,90.294,91.024,98.641,104.820,109.837,108.826,98.717
609,8180,Senegal,"Gross domestic product (GDP), Constant prices,...",CFA franc,3483.268,3659.852,3946.897,3736.670,3876.637,4003.925,...,14797.900,15427.910,16424.893,17522.450,NaN,NaN,NaN,NaN,NaN,NaN
610,8186,Seychelles,"Gross domestic product (GDP), Constant prices,...",Seychelles rupee,5.342,5.135,5.029,4.998,5.213,5.750,...,24.942,26.233,27.112,28.678,28.971,30.137,31.084,32.048,33.062,34.119
611,8187,Seychelles,"Gross domestic product (GDP), Constant prices,...",Seychelles rupee,-2.253,-3.877,-2.071,-0.616,4.306,10.294,...,9.877,5.176,3.351,5.776,1.020,4.027,3.141,3.101,3.164,3.197
612,8191,Seychelles,"Gross debt, General government, Percent of GDP",Seychelles rupee,NaN,NaN,NaN,NaN,NaN,NaN,...,60.563,55.106,56.252,51.205,52.747,51.980,51.043,49.965,48.810,47.705

In [76]:
df3 = df3.drop(columns = 'index')

In [77]:
df3

,COUNTRY,Indicator,PRIMARY_DOMESTIC_CURRENCY,1980,1981,1982,1983,1984,1985,1986,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,Syrian Arab Republic,"Gross debt, General government, Percent of GDP",Syrian pound,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Syrian Arab Republic,"Gross domestic product (GDP), Constant prices,...",Syrian pound,464.241,503.530,516.534,524.824,490.720,526.524,501.478,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Syrian Arab Republic,"Gross domestic product (GDP), Constant prices,...",Syrian pound,10.493,8.463,2.583,1.605,-6.498,7.296,-4.757,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Eritrea, The State of","Gross domestic product (GDP), Constant prices,...",Eritrean nakfa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Eritrea, The State of","Gross domestic product (GDP), Constant prices,...",Eritrean nakfa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,"Mozambique, Republic of","Gross debt, General government, Percent of GDP",Mozambican metical,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,97.307,90.828,91.192,90.294,91.024,98.641,104.820,109.837,108.826,98.717
609,Senegal,"Gross domestic product (GDP), Constant prices,...",CFA franc,3483.268,3659.852,3946.897,3736.670,3876.637,4003.925,4128.581,...,14797.900,15427.910,16424.893,17522.450,NaN,NaN,NaN,NaN,NaN,NaN
610,Seychelles,"Gross domestic product (GDP), Constant prices,...",Seychelles rupee,5.342,5.135,5.029,4.998,5.213,5.750,5.793,...,24.942,26.233,27.112,28.678,28.971,30.137,31.084,32.048,33.062,34.119
611,Seychelles,"Gross domestic product (GDP), Constant prices,...",Seychelles rupee,-2.253,-3.877,-2.071,-0.616,4.306,10.294,0.762,...,9.877,5.176,3.351,5.776,1.020,4.027,3.141,3.101,3.164,3.197
612,Seychelles,"Gross debt, General government, Percent of GDP",Seychelles rupee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,60.563,55.106,56.252,51.205,52.747,51.980,51.043,49.965,48.810,47.705

In [78]:
##alle Daten aus dem 20. Jahrhundert löschen

df3 = df3.drop(columns=['1980','1981','1982','1983','1984','1985','1986','1987','1988','1989','1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000']).copy()

In [79]:
df3

,COUNTRY,Indicator,PRIMARY_DOMESTIC_CURRENCY,2001,2002,2003,2004,2005,2006,2007,...,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031
0,Syrian Arab Republic,"Gross debt, General government, Percent of GDP",Syrian pound,144.490,132.427,133.370,113.047,50.710,44.977,42.672,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Syrian Arab Republic,"Gross domestic product (GDP), Constant prices,...",Syrian pound,981.983,1039.888,1018.708,1089.026,1156.714,1215.082,1284.035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Syrian Arab Republic,"Gross domestic product (GDP), Constant prices,...",Syrian pound,3.680,5.897,-2.037,6.903,6.215,5.046,5.675,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Eritrea, The State of","Gross domestic product (GDP), Constant prices,...",Eritrean nakfa,8.755,3.005,-2.656,1.452,2.574,-0.969,1.427,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Eritrea, The State of","Gross domestic product (GDP), Constant prices,...",Eritrean nakfa,24.053,24.776,24.118,24.468,25.098,24.855,25.210,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,"Mozambique, Republic of","Gross debt, General government, Percent of GDP",Mozambican metical,99.766,63.351,63.157,50.767,60.084,40.029,31.181,...,97.307,90.828,91.192,90.294,91.024,98.641,104.820,109.837,108.826,98.717
609,Senegal,"Gross domestic product (GDP), Constant prices,...",CFA franc,6376.569,6380.950,6737.897,7050.757,7354.662,7526.082,7738.853,...,14797.900,15427.910,16424.893,17522.450,NaN,NaN,NaN,NaN,NaN,NaN
610,Seychelles,"Gross domestic product (GDP), Constant prices,...",Seychelles rupee,11.532,11.672,10.985,10.672,11.633,12.727,14.053,...,24.942,26.233,27.112,28.678,28.971,30.137,31.084,32.048,33.062,34.119
611,Seychelles,"Gross domestic product (GDP), Constant prices,...",Seychelles rupee,-2.271,1.213,-5.887,-2.850,9.006,9.406,10.418,...,9.877,5.176,3.351,5.776,1.020,4.027,3.141,3.101,3.164,3.197
612,Seychelles,"Gross debt, General government, Percent of GDP",Seychelles rupee,199.787,195.860,176.975,163.226,144.064,135.071,143.997,...,60.563,55.106,56.252,51.205,52.747,51.980,51.043,49.965,48.810,47.705

In [80]:
##Funktion schreiben zum löschen

def c_löschen(df, c):
    return df.drop(columns=c)

In [81]:
##welche Länder kommen in Frage?
df3['COUNTRY'].unique()

array(['Syrian Arab Republic', 'Eritrea, The State of', 'Sierra Leone',
       'Senegal', 'Sudan', 'Namibia', 'South Sudan, Republic of',
       'Somalia', 'Tanzania, United Republic of', 'Togo',
       'Eswatini, Kingdom of', 'Tunisia', 'Uganda', 'Burkina Faso',
       'Zambia', 'Naoero, Republic of', 'Kiribati', 'Solomon Islands',
       'Fiji, Republic of', 'Tuvalu', 'Papua New Guinea', 'Samoa',
       'Vanuatu', 'Tonga', 'Armenia, Republic of',
       'Marshall Islands, Republic of the',
       'Micronesia, Federated States of', 'Albania',
       'Kazakhstan, Republic of', 'Georgia', 'Belarus, Republic of',
       'Azerbaijan, Republic of', 'Emerging and Developing Europe',
       'Kyrgyz Republic', 'Moldova, Republic of', 'Bulgaria', 'Ukraine',
       'Turkmenistan', 'Russian Federation', 'Tajikistan, Republic of',
       "China, People's Republic of", 'Slovak Republic',
       'Estonia, Republic of', 'Uzbekistan, Republic of',
       'Czech Republic', 'Latvia, Republic of', 'Mongolia', 'Montenegro',
       'Serbia, Republic of', 'Hungary', 'North Macedonia, Republic of',
       'Lithuania, Republic of', 'Croatia, Republic of',
       'Bosnia and Herzegovina', 'Slovenia, Republic of',
       'Kosovo, Republic of', 'Poland, Republic of', 'Romania',
       'European Union (EU)', 'Libya', 'Advanced Economies', 'World',
       'United Kingdom', 'United States', 'G7', 'Belgium', 'Austria',
       'Other Advanced Economies (Advanced Economies excluding G7 and Euro Area countries)',
       'Germany', 'Denmark', 'France', 'Luxembourg',
       'San Marino, Republic of', 'Italy', 'Sweden', 'Norway',
       'Netherlands, The', 'Liechtenstein, Principality of',
       'Switzerland', 'Canada', 'Japan', 'Finland',
       'Andorra, Principality of', 'Euro Area (EA)', 'Iceland', 'Greece',
       'Ireland', 'Spain', 'Portugal', 'Malta', 'New Zealand',
       'Australia', 'Türkiye, Republic of', 'South Africa',
       'Emerging Market and Developing Economies',
       'Latin America and the Caribbean (LAC)', 'Argentina', 'Bolivia',
       'Brazil', 'Colombia', 'Chile', 'Costa Rica', 'El Salvador',
       'Guatemala', 'Dominican Republic', 'Ecuador', 'Haiti', 'Mexico',
       'Honduras', 'Panama', 'Nicaragua', 'Paraguay', 'Peru', 'Uruguay',
       'Antigua and Barbuda', 'Venezuela, República Bolivariana de',
       'Bahamas, The', 'Aruba, Kingdom of the Netherlands', 'Dominica',
       'Grenada', 'Guyana', 'Barbados', 'St. Vincent and the Grenadines',
       'Puerto Rico', 'Jamaica', 'Belize', 'St. Kitts and Nevis',
       'Suriname', 'St. Lucia', 'Bahrain, Kingdom of',
       'Trinidad and Tobago', 'Middle East and Central Asia',
       'Iran, Islamic Republic of', 'Cyprus', 'Iraq', 'Kuwait', 'Jordan',
       'Israel', 'Qatar', 'Oman', 'Lebanon', 'Saudi Arabia',
       'United Arab Emirates', 'Egypt, Arab Republic of', 'Bangladesh',
       'Yemen, Republic of', 'West Bank and Gaza',
       'Emerging and Developing Asia', 'Bhutan',
       'Afghanistan, Islamic Republic of', 'ASEAN-5',
       "Hong Kong Special Administrative Region, People's Republic of China",
       'Taiwan Province of China', 'Cambodia', 'Brunei Darussalam',
       'Myanmar', 'Sri Lanka', "Lao People's Democratic Republic",
       'Indonesia', 'Korea, Republic of',
       'Timor-Leste, Democratic Republic of', 'India', 'Nepal',
       'Maldives', 'Malaysia',
       "Macao Special Administrative Region, People's Republic of China",
       'Pakistan', 'Palau, Republic of', 'Singapore', 'Thailand',
       'Philippines', 'Sub-Saharan Africa (SSA)', 'Botswana', 'Algeria',
       'Angola', 'Vietnam', 'Djibouti', 'Congo, Republic of',
       'Comoros, Union of the', 'Cabo Verde', 'Burundi', 'Cameroon',
       'Central African Republic', 'Benin',
       'Equatorial Guinea, Republic of', 'Chad',
       'Congo, Democratic Republic of the', 'Gambia, The', 'Guinea',
       'Gabon', 'Ethiopia, The Federal Democratic Republic of',
       'Lesotho, Kingdom of', 'Guinea-Bissau', 'Ghana', 'Malawi',
       'Madagascar, Republic of', "Côte d'Ivoire", 'Kenya', 'Liberia',
       'Mauritania, Islamic Republic of', 'Mauritius', 'Mali', 'Morocco',
       'Rwanda', 'São Tomé and Príncipe, Democratic Republic of',
       'Nigeria', 'Niger', 'Mozambique, Republic of', 'Zimbabwe',
       'Seychelles'], dtype=object)

In [82]:
oecd_countries = [
    'Australia',
    'Austria',
    'Belgium',
    'Canada',
    'Chile',
    'Colombia',
    'Costa Rica',
    'Czech Republic',
    'Denmark',
    'Estonia, Republic of',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'Ireland',
    'Israel',
    'Italy',
    'Japan',
    'Korea, Republic of',
    'Latvia, Republic of',
    'Lithuania, Republic of',
    'Luxembourg',
    'Mexico',
    'Netherlands, The',
    'New Zealand',
    'Norway',
    'Poland, Republic of',
    'Portugal',
    'Slovak Republic',
    'Slovenia, Republic of',
    'Spain',
    'Sweden',
    'Switzerland',
    'Türkiye, Republic of',
    'United Kingdom',
    'United States'
]

In [83]:
df3 = df3.loc[(df3['COUNTRY'].isin(oecd_countries)), :].copy()

In [84]:
df3 = df3.reset_index(drop=True)

In [85]:
liste = [i for i in range(2026, 2032)]
liste

[2026, 2027, 2028, 2029, 2030, 2031]

In [86]:
liste = [str(i) for i in liste]
liste

['2026', '2027', '2028', '2029', '2030', '2031']

In [87]:
df3 = df3.drop(columns = liste)

In [88]:
df3

,COUNTRY,Indicator,PRIMARY_DOMESTIC_CURRENCY,2001,2002,2003,2004,2005,2006,2007,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Slovak Republic,"Gross domestic product (GDP), Constant prices,...",Euro,48.538,50.682,53.144,56.008,59.640,64.964,71.992,...,88.432,90.974,94.669,96.824,94.321,99.655,100.198,102.315,104.298,105.141
1,"Estonia, Republic of","Gross debt, General government, Percent of GDP",Euro,4.933,5.660,5.599,5.159,4.733,4.717,3.908,...,10.239,9.434,8.507,9.047,19.098,18.425,19.112,20.274,23.451,23.965
2,Czech Republic,"Gross debt, General government, Percent of GDP",Czech koruna,22.597,25.703,28.062,28.289,27.678,27.565,27.346,...,36.232,33.782,31.678,29.552,36.883,40.692,42.520,42.223,43.232,44.166
3,Czech Republic,"Gross domestic product (GDP), Constant prices,...",Czech koruna,3750.216,3806.974,3932.636,4118.899,4381.480,4671.673,4928.093,...,5495.050,5779.340,5942.913,6154.824,5828.318,6063.142,6235.770,6238.737,6320.676,6486.784
4,"Latvia, Republic of","Gross domestic product (GDP), Constant prices,...",Euro,16.482,17.745,19.241,20.920,23.350,26.345,29.088,...,27.881,28.829,30.072,30.275,29.224,31.253,31.850,31.550,31.538,32.212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,Israel,"Gross debt, General government, Percent of GDP",Israeli new shekel,81.416,87.642,90.048,88.734,85.669,78.047,71.201,...,62.040,60.125,60.340,59.543,71.376,68.193,60.884,61.920,67.677,67.869
110,Israel,"Gross domestic product (GDP), Constant prices,...",Israeli new shekel,0.318,-0.250,1.563,4.567,4.300,5.598,6.263,...,4.544,4.339,4.108,3.645,-1.884,8.956,6.147,2.049,1.711,3.486
111,"Korea, Republic of","Gross debt, General government, Percent of GDP",South Korean won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39.144,38.011,37.854,39.730,45.915,47.949,49.704,50.562,49.558,52.417
112,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,1045467.700,1126428.700,1161063.300,1221248.600,1274473.400,1341319.600,1419679.000,...,1898551.100,1963732.000,2026102.400,2072982.300,2058466.400,2155142.800,2217828.200,2250707.400,2300068.700,2326267.400
113,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,4.726,7.744,3.075,5.184,4.358,5.245,5.842,...,3.172,3.433,3.176,2.314,-0.700,4.697,2.909,1.482,2.193,1.139

In [89]:
df3 = df3.rename(columns = {'COUNTRY':'country'})

In [90]:
df3.shape

(114, 28)

In [ ]:
##Test1: Hat jedes Land tatsächlich 3 Indikatoren? -> mit GroupBy

In [93]:
#country umbennenen

df3 = df3.rename(columns = {'COUNTRY' : 'Country'})
df3

,country,Indicator,PRIMARY_DOMESTIC_CURRENCY,2001,2002,2003,2004,2005,2006,2007,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Slovak Republic,"Gross domestic product (GDP), Constant prices,...",Euro,48.538,50.682,53.144,56.008,59.640,64.964,71.992,...,88.432,90.974,94.669,96.824,94.321,99.655,100.198,102.315,104.298,105.141
1,"Estonia, Republic of","Gross debt, General government, Percent of GDP",Euro,4.933,5.660,5.599,5.159,4.733,4.717,3.908,...,10.239,9.434,8.507,9.047,19.098,18.425,19.112,20.274,23.451,23.965
2,Czech Republic,"Gross debt, General government, Percent of GDP",Czech koruna,22.597,25.703,28.062,28.289,27.678,27.565,27.346,...,36.232,33.782,31.678,29.552,36.883,40.692,42.520,42.223,43.232,44.166
3,Czech Republic,"Gross domestic product (GDP), Constant prices,...",Czech koruna,3750.216,3806.974,3932.636,4118.899,4381.480,4671.673,4928.093,...,5495.050,5779.340,5942.913,6154.824,5828.318,6063.142,6235.770,6238.737,6320.676,6486.784
4,"Latvia, Republic of","Gross domestic product (GDP), Constant prices,...",Euro,16.482,17.745,19.241,20.920,23.350,26.345,29.088,...,27.881,28.829,30.072,30.275,29.224,31.253,31.850,31.550,31.538,32.212
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,Israel,"Gross debt, General government, Percent of GDP",Israeli new shekel,81.416,87.642,90.048,88.734,85.669,78.047,71.201,...,62.040,60.125,60.340,59.543,71.376,68.193,60.884,61.920,67.677,67.869
110,Israel,"Gross domestic product (GDP), Constant prices,...",Israeli new shekel,0.318,-0.250,1.563,4.567,4.300,5.598,6.263,...,4.544,4.339,4.108,3.645,-1.884,8.956,6.147,2.049,1.711,3.486
111,"Korea, Republic of","Gross debt, General government, Percent of GDP",South Korean won,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,39.144,38.011,37.854,39.730,45.915,47.949,49.704,50.562,49.558,52.417
112,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,1045467.700,1126428.700,1161063.300,1221248.600,1274473.400,1341319.600,1419679.000,...,1898551.100,1963732.000,2026102.400,2072982.300,2058466.400,2155142.800,2217828.200,2250707.400,2300068.700,2326267.400
113,"Korea, Republic of","Gross domestic product (GDP), Constant prices,...",South Korean won,4.726,7.744,3.075,5.184,4.358,5.245,5.842,...,3.172,3.433,3.176,2.314,-0.700,4.697,2.909,1.482,2.193,1.139

In [97]:
## weietere Schritte bevor die nAn untersucht werden
## einzelne Kontrollen
## Aufgabe: haben alle Länder wirklich 3 INdikatoren?


n = df3.groupby('country')['Indicator'].nunique()
n

country
Australia                 3
Austria                   3
Belgium                   3
Canada                    3
Chile                     3
Colombia                  3
Costa Rica                3
Czech Republic            3
Denmark                   3
Estonia, Republic of      3
Finland                   3
France                    3
Germany                   3
Greece                    3
Hungary                   3
Iceland                   3
Ireland                   3
Israel                    3
Italy                     3
Japan                     3
Korea, Republic of        3
Latvia, Republic of       3
Lithuania, Republic of    3
Luxembourg                3
Mexico                    3
Netherlands, The          3
New Zealand               3
Norway                    3
Poland, Republic of       3
Portugal                  3
Slovak Republic           3
Slovenia, Republic of     3
Spain                     3
Sweden                    3
Switzerland               3
Türkiye, Republic of      3
United Kingdom            3
United States             3
Name: Indicator, dtype: int64

In [98]:
n = df3.groupby('country')['Indicator'].nunique().value_counts()
n

##gemäß n alles in ordnung

Indicator
3    38
Name: count, dtype: int64

In [100]:
df3['country'].value_counts()

country
Slovak Republic           3
Portugal                  3
Canada                    3
Japan                     3
Finland                   3
Iceland                   3
Greece                    3
Ireland                   3
Spain                     3
New Zealand               3
Estonia, Republic of      3
Australia                 3
Türkiye, Republic of      3
Colombia                  3
Chile                     3
Costa Rica                3
Mexico                    3
Israel                    3
Switzerland               3
Netherlands, The          3
Norway                    3
Sweden                    3
Czech Republic            3
Latvia, Republic of       3
Hungary                   3
Lithuania, Republic of    3
Slovenia, Republic of     3
Poland, Republic of       3
United Kingdom            3
United States             3
Belgium                   3
Austria                   3
Germany                   3
Denmark                   3
France                    3
Luxembourg                3
Italy                     3
Korea, Republic of        3
Name: count, dtype: int64

In [101]:
##nächster Schritt: nAn

df3.isna().sum()

country                      0
Indicator                    0
PRIMARY_DOMESTIC_CURRENCY    0
2001                         1
2002                         1
2003                         1
2004                         1
2005                         1
2006                         1
2007                         1
2008                         1
2009                         1
2010                         1
2011                         1
2012                         0
2013                         0
2014                         0
2015                         0
2016                         0
2017                         0
2018                         0
2019                         0
2020                         0
2021                         0
2022                         0
2023                         0
2024                         0
2025                         0
dtype: int64

In [103]:
df3.isna()

,country,Indicator,PRIMARY_DOMESTIC_CURRENCY,2001,2002,2003,2004,2005,2006,2007,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
110,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
111,False,False,False,True,True,True,True,True,True,True,...,False,False,False,False,False,False,False,False,False,False
112,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
113,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [105]:
df3.iloc[111, :]

country                                                  Korea, Republic of
Indicator                    Gross debt, General government, Percent of GDP
PRIMARY_DOMESTIC_CURRENCY                                  South Korean won
2001                                                                    NaN
2002                                                                    NaN
2003                                                                    NaN
2004                                                                    NaN
2005                                                                    NaN
2006                                                                    NaN
2007                                                                    NaN
2008                                                                    NaN
2009                                                                    NaN
2010                                                                    NaN
2011                                                                    NaN
2012                                                                 33.536
2013                                                                 36.007
2014                                                                 37.875
2015                                                                 38.843
2016                                                                 39.144
2017                                                                 38.011
2018                                                                 37.854
2019                                                                  39.73
2020                                                                 45.915
2021                                                                 47.949
2022                                                                 49.704
2023                                                                 50.562
2024                                                                 49.558
2025                                                                 52.417
Name: 111, dtype: object

In [107]:
df3['Indicator'].unique()

array(['Gross domestic product (GDP), Constant prices, Domestic currency',
       'Gross debt, General government, Percent of GDP',
       'Gross domestic product (GDP), Constant prices, Percent change'],
      dtype=object)

In [108]:
##Extraktion in eine csv-Datei

df3.to_csv('IWF_bereinigt.csv', index = False)